# -*- mode: python ; coding: utf-8 -*-

import os
import PySide6

block_cipher = None

qt_plugins_dir = os.path.join(os.path.dirname(PySide6.__file__), 'plugins')

a = Analysis(
    ['sperm_counter_gui_onnx.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('runs/detect/sperm_detection/weights/best.onnx', '.'),
        (os.path.join(qt_plugins_dir, 'platforms'), 'platforms'),
    ],
    hiddenimports=[
        'onnxruntime',
        'onnxruntime.capi',
        'onnxruntime.capi._pybind_state',
        'cv2',
        'numpy',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'pandas',
        'tkinter',
        'PIL',
        'IPython',
        'torch',
        'torchvision',
        'ultralytics',
        'sklearn',
        'seaborn',
        'plotly',
        'networkx',
        'sympy',
        'pygame',
        'pyqt5',
        'wx',
        'xmlrpc',
        'smtplib',
        'email',
        'urllib3',
        'requests',
        'beautifulsoup4',
        'sqlalchemy',
        'psycopg2',
        'mysql',
        'boto3',
        'google',
        'aws',
        'azure',
        'tensorflow',
        'keras',
        'jax',
        'mxnet',
        'openvino',
        'paddlepaddle',
        'setuptools',
        'pip',
        'wheel',
        'pip._vendor',
        'pkg_resources',
        'unittest',
        'doctest',
        'pdb',
        'curses',
        'readline',
        'rlcompleter',
        'charset_normalizer.md__mypyc',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SpermCounter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='SpermCounter',
)
