# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['sperm_counter_gui_onnx.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('runs/detect/sperm_detection/weights/best.onnx', '.'),
    ],
    hiddenimports=[
        'onnxruntime',
        'onnxruntime.capi',
        'onnxruntime.capi._pybind_state',
        'cv2',
        'numpy',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'pandas',
        'tkinter',
        'PIL',
        'IPython',
        'torch',
        'torchvision',
        'ultralytics',
        'sklearn',
        'seaborn',
        'plotly',
        'networkx',
        'sympy',
        'pygame',
        'pyqt5',
        'wx',
        'xmlrpc',
        'smtplib',
        'email',
        'urllib3',
        'requests',
        'beautifulsoup4',
        'sqlalchemy',
        'psycopg2',
        'mysql',
        'boto3',
        'google',
        'aws',
        'azure',
        'tensorflow',
        'keras',
        'jax',
        'mxnet',
        'openvino',
        'paddlepaddle',
        'setuptools',
        'pip',
        'wheel',
        'pip._vendor',
        'pkg_resources',
        'unittest',
        'doctest',
        'pdb',
        'curses',
        'readline',
        'rlcompleter',
        'PySide6.QtDBus',
        'PySide6.QtXml',
        'PySide6.QtSql',
        'PySide6.QtTest',
        'PySide6.QtBluetooth',
        'PySide6.QtDesigner',
        'PySide6.QtHelp',
        'PySide6.QtLocation',
        'PySide6.QtMultimedia',
        'PySide6.QtMultimediaWidgets',
        'PySide6.QtNfc',
        'PySide6.QtPositioning',
        'PySide6.QtPrintSupport',
        'PySide6.QtQml',
        'PySide6.QtQuick',
        'PySide6.QtQuickWidgets',
        'PySide6.QtRemoteObjects',
        'PySide6.QtScxml',
        'PySide6.QtSensors',
        'PySide6.QtSerialPort',
        'PySide6.QtSql',
        'PySide6.QtSvg',
        'PySide6.QtSvgWidgets',
        'PySide6.QtWebChannel',
        'PySide6.QtWebSockets',
        'PySide6.QtXmlPatterns',
        'charset_normalizer.md__mypyc',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='SpermCounter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='SpermCounter',
)

app = BUNDLE(
    coll,
    name='SpermCounter.app',
    icon=None,
    bundle_identifier=None,
    info_plist={
        'NSHighResolutionCapable': 'True',
        'CFBundleDisplayName': '精子染色状态统计工具',
        'CFBundleName': 'SpermCounter',
        'CFBundleShortVersionString': '1.0.0',
        'CFBundleVersion': '1.0.0',
        'CFBundleIdentifier': 'com.example.SpermCounter',
        'LSMinimumSystemVersion': '10.13',
    },
)
